// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImageFullHD.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ImageFullHD.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


ImageFullHD::ImageFullHD()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@61009542

    // m_frame com.eprosima.idl.parser.typecode.ArrayTypeCode@77e9807f
    memset(&m_frame, 0, (fullhd_img_size) * 1);

}

ImageFullHD::~ImageFullHD()
{


}

ImageFullHD::ImageFullHD(
        const ImageFullHD& x)
{
    m_header = x.m_header;
    m_frame = x.m_frame;
}

ImageFullHD::ImageFullHD(
        ImageFullHD&& x)
{
    m_header = std::move(x.m_header);
    m_frame = std::move(x.m_frame);
}

ImageFullHD& ImageFullHD::operator =(
        const ImageFullHD& x)
{

    m_header = x.m_header;
    m_frame = x.m_frame;

    return *this;
}

ImageFullHD& ImageFullHD::operator =(
        ImageFullHD&& x)
{

    m_header = std::move(x.m_header);
    m_frame = std::move(x.m_frame);

    return *this;
}

size_t ImageFullHD::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += ((fullhd_img_size) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t ImageFullHD::getCdrSerializedSize(
        const ImageFullHD& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.header(), current_alignment);
    if ((fullhd_img_size) > 0)
    {
        current_alignment += ((fullhd_img_size) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }


    return current_alignment - initial_alignment;
}

void ImageFullHD::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_frame;


}

void ImageFullHD::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_frame;

}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void ImageFullHD::header(
        const Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void ImageFullHD::header(
        Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const Header& ImageFullHD::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
Header& ImageFullHD::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member frame
 * @param _frame New value to be copied in member frame
 */
void ImageFullHD::frame(
        const std::array<uint8_t, fullhd_img_size>& _frame)
{
    m_frame = _frame;
}

/*!
 * @brief This function moves the value in member frame
 * @param _frame New value to be moved in member frame
 */
void ImageFullHD::frame(
        std::array<uint8_t, fullhd_img_size>&& _frame)
{
    m_frame = std::move(_frame);
}

/*!
 * @brief This function returns a constant reference to member frame
 * @return Constant reference to member frame
 */
const std::array<uint8_t, fullhd_img_size>& ImageFullHD::frame() const
{
    return m_frame;
}

/*!
 * @brief This function returns a reference to member frame
 * @return Reference to member frame
 */
std::array<uint8_t, fullhd_img_size>& ImageFullHD::frame()
{
    return m_frame;
}

size_t ImageFullHD::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool ImageFullHD::isKeyDefined()
{
    return false;
}

void ImageFullHD::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
