// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImageHD.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ImageHD.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

ImageHD::ImageHD()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@226a82c4

    // m_frame com.eprosima.idl.parser.typecode.ArrayTypeCode@731f8236
    memset(&m_frame, 0, (311) * 1);

}

ImageHD::~ImageHD()
{


}

ImageHD::ImageHD(
        const ImageHD& x)
{
    m_header = x.m_header;
    m_frame = x.m_frame;
}

ImageHD::ImageHD(
        ImageHD&& x)
{
    m_header = std::move(x.m_header);
    m_frame = std::move(x.m_frame);
}

ImageHD& ImageHD::operator =(
        const ImageHD& x)
{

    m_header = x.m_header;
    m_frame = x.m_frame;

    return *this;
}

ImageHD& ImageHD::operator =(
        ImageHD&& x)
{

    m_header = std::move(x.m_header);
    m_frame = std::move(x.m_frame);

    return *this;
}

size_t ImageHD::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += ((311) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t ImageHD::getCdrSerializedSize(
        const ImageHD& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.header(), current_alignment);
    if ((311) > 0)
    {
        current_alignment += ((311) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }


    return current_alignment - initial_alignment;
}

void ImageHD::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_frame;


}

void ImageHD::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_frame;

}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void ImageHD::header(
        const Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void ImageHD::header(
        Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const Header& ImageHD::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
Header& ImageHD::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member frame
 * @param _frame New value to be copied in member frame
 */
void ImageHD::frame(
        const std::array<uint8_t, 311>& _frame)
{
    m_frame = _frame;
}

/*!
 * @brief This function moves the value in member frame
 * @param _frame New value to be moved in member frame
 */
void ImageHD::frame(
        std::array<uint8_t, 311>&& _frame)
{
    m_frame = std::move(_frame);
}

/*!
 * @brief This function returns a constant reference to member frame
 * @return Constant reference to member frame
 */
const std::array<uint8_t, 311>& ImageHD::frame() const
{
    return m_frame;
}

/*!
 * @brief This function returns a reference to member frame
 * @return Reference to member frame
 */
std::array<uint8_t, 311>& ImageHD::frame()
{
    return m_frame;
}

size_t ImageHD::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool ImageHD::isKeyDefined()
{
    return false;
}

void ImageHD::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
