// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file QuadActionCmd.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "QuadActionCmd.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

idl_msg::QuadActionCmd::QuadActionCmd()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@2b6856dd

    // m_cmd com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5db45159
    m_cmd = 0;

}

idl_msg::QuadActionCmd::~QuadActionCmd()
{


}

idl_msg::QuadActionCmd::QuadActionCmd(
        const QuadActionCmd& x)
{
    m_header = x.m_header;
    m_cmd = x.m_cmd;
}

idl_msg::QuadActionCmd::QuadActionCmd(
        QuadActionCmd&& x)
{
    m_header = std::move(x.m_header);
    m_cmd = x.m_cmd;
}

idl_msg::QuadActionCmd& idl_msg::QuadActionCmd::operator =(
        const QuadActionCmd& x)
{

    m_header = x.m_header;
    m_cmd = x.m_cmd;

    return *this;
}

idl_msg::QuadActionCmd& idl_msg::QuadActionCmd::operator =(
        QuadActionCmd&& x)
{

    m_header = std::move(x.m_header);
    m_cmd = x.m_cmd;

    return *this;
}

size_t idl_msg::QuadActionCmd::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += idl_msg::Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t idl_msg::QuadActionCmd::getCdrSerializedSize(
        const idl_msg::QuadActionCmd& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += idl_msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void idl_msg::QuadActionCmd::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_cmd;

}

void idl_msg::QuadActionCmd::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_cmd;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void idl_msg::QuadActionCmd::header(
        const idl_msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void idl_msg::QuadActionCmd::header(
        idl_msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const idl_msg::Header& idl_msg::QuadActionCmd::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
idl_msg::Header& idl_msg::QuadActionCmd::header()
{
    return m_header;
}
/*!
 * @brief This function sets a value in member cmd
 * @param _cmd New value for member cmd
 */
void idl_msg::QuadActionCmd::cmd(
        uint8_t _cmd)
{
    m_cmd = _cmd;
}

/*!
 * @brief This function returns the value of member cmd
 * @return Value of member cmd
 */
uint8_t idl_msg::QuadActionCmd::cmd() const
{
    return m_cmd;
}

/*!
 * @brief This function returns a reference to member cmd
 * @return Reference to member cmd
 */
uint8_t& idl_msg::QuadActionCmd::cmd()
{
    return m_cmd;
}


size_t idl_msg::QuadActionCmd::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool idl_msg::QuadActionCmd::isKeyDefined()
{
    return false;
}

void idl_msg::QuadActionCmd::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}

