// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file QuadMotorCommand.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "QuadMotorCommand.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

QuadMotorCommand::QuadMotorCommand()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@56de5251

    // m_motorspeed com.eprosima.idl.parser.typecode.ArrayTypeCode@419c5f1a
    memset(&m_motorspeed, 0, (4) * 4);

}

QuadMotorCommand::~QuadMotorCommand()
{


}

QuadMotorCommand::QuadMotorCommand(
        const QuadMotorCommand& x)
{
    m_header = x.m_header;
    m_motorspeed = x.m_motorspeed;
}

QuadMotorCommand::QuadMotorCommand(
        QuadMotorCommand&& x)
{
    m_header = std::move(x.m_header);
    m_motorspeed = std::move(x.m_motorspeed);
}

QuadMotorCommand& QuadMotorCommand::operator =(
        const QuadMotorCommand& x)
{

    m_header = x.m_header;
    m_motorspeed = x.m_motorspeed;

    return *this;
}

QuadMotorCommand& QuadMotorCommand::operator =(
        QuadMotorCommand&& x)
{

    m_header = std::move(x.m_header);
    m_motorspeed = std::move(x.m_motorspeed);

    return *this;
}

size_t QuadMotorCommand::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += ((4) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t QuadMotorCommand::getCdrSerializedSize(
        const QuadMotorCommand& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.header(), current_alignment);
    if ((4) > 0)
    {
        current_alignment += ((4) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }


    return current_alignment - initial_alignment;
}

void QuadMotorCommand::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_motorspeed;


}

void QuadMotorCommand::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_motorspeed;

}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void QuadMotorCommand::header(
        const Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void QuadMotorCommand::header(
        Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const Header& QuadMotorCommand::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
Header& QuadMotorCommand::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member motorspeed
 * @param _motorspeed New value to be copied in member motorspeed
 */
void QuadMotorCommand::motorspeed(
        const std::array<float, 4>& _motorspeed)
{
    m_motorspeed = _motorspeed;
}

/*!
 * @brief This function moves the value in member motorspeed
 * @param _motorspeed New value to be moved in member motorspeed
 */
void QuadMotorCommand::motorspeed(
        std::array<float, 4>&& _motorspeed)
{
    m_motorspeed = std::move(_motorspeed);
}

/*!
 * @brief This function returns a constant reference to member motorspeed
 * @return Constant reference to member motorspeed
 */
const std::array<float, 4>& QuadMotorCommand::motorspeed() const
{
    return m_motorspeed;
}

/*!
 * @brief This function returns a reference to member motorspeed
 * @return Reference to member motorspeed
 */
std::array<float, 4>& QuadMotorCommand::motorspeed()
{
    return m_motorspeed;
}

size_t QuadMotorCommand::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool QuadMotorCommand::isKeyDefined()
{
    return false;
}

void QuadMotorCommand::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
