// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file QuadAttitudeRateCommand.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "QuadAttitudeRateCommand.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

idl_msg::QuadAttitudeRateCommand::QuadAttitudeRateCommand()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@27c86f2d

    // m_thrust com.eprosima.idl.parser.typecode.PrimitiveTypeCode@79ad8b2f
    m_thrust = 0.0;
    // m_roll_rate com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1df82230
    m_roll_rate = 0.0;
    // m_pitch_rate com.eprosima.idl.parser.typecode.PrimitiveTypeCode@22635ba0
    m_pitch_rate = 0.0;
    // m_yaw_rate com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5a955565
    m_yaw_rate = 0.0;

}

idl_msg::QuadAttitudeRateCommand::~QuadAttitudeRateCommand()
{





}

idl_msg::QuadAttitudeRateCommand::QuadAttitudeRateCommand(
        const QuadAttitudeRateCommand& x)
{
    m_header = x.m_header;
    m_thrust = x.m_thrust;
    m_roll_rate = x.m_roll_rate;
    m_pitch_rate = x.m_pitch_rate;
    m_yaw_rate = x.m_yaw_rate;
}

idl_msg::QuadAttitudeRateCommand::QuadAttitudeRateCommand(
        QuadAttitudeRateCommand&& x)
{
    m_header = std::move(x.m_header);
    m_thrust = x.m_thrust;
    m_roll_rate = x.m_roll_rate;
    m_pitch_rate = x.m_pitch_rate;
    m_yaw_rate = x.m_yaw_rate;
}

idl_msg::QuadAttitudeRateCommand& idl_msg::QuadAttitudeRateCommand::operator =(
        const QuadAttitudeRateCommand& x)
{

    m_header = x.m_header;
    m_thrust = x.m_thrust;
    m_roll_rate = x.m_roll_rate;
    m_pitch_rate = x.m_pitch_rate;
    m_yaw_rate = x.m_yaw_rate;

    return *this;
}

idl_msg::QuadAttitudeRateCommand& idl_msg::QuadAttitudeRateCommand::operator =(
        QuadAttitudeRateCommand&& x)
{

    m_header = std::move(x.m_header);
    m_thrust = x.m_thrust;
    m_roll_rate = x.m_roll_rate;
    m_pitch_rate = x.m_pitch_rate;
    m_yaw_rate = x.m_yaw_rate;

    return *this;
}

size_t idl_msg::QuadAttitudeRateCommand::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += idl_msg::Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t idl_msg::QuadAttitudeRateCommand::getCdrSerializedSize(
        const idl_msg::QuadAttitudeRateCommand& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += idl_msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void idl_msg::QuadAttitudeRateCommand::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_thrust;
    scdr << m_roll_rate;
    scdr << m_pitch_rate;
    scdr << m_yaw_rate;

}

void idl_msg::QuadAttitudeRateCommand::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_thrust;
    dcdr >> m_roll_rate;
    dcdr >> m_pitch_rate;
    dcdr >> m_yaw_rate;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void idl_msg::QuadAttitudeRateCommand::header(
        const idl_msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void idl_msg::QuadAttitudeRateCommand::header(
        idl_msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const idl_msg::Header& idl_msg::QuadAttitudeRateCommand::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
idl_msg::Header& idl_msg::QuadAttitudeRateCommand::header()
{
    return m_header;
}
/*!
 * @brief This function sets a value in member thrust
 * @param _thrust New value for member thrust
 */
void idl_msg::QuadAttitudeRateCommand::thrust(
        float _thrust)
{
    m_thrust = _thrust;
}

/*!
 * @brief This function returns the value of member thrust
 * @return Value of member thrust
 */
float idl_msg::QuadAttitudeRateCommand::thrust() const
{
    return m_thrust;
}

/*!
 * @brief This function returns a reference to member thrust
 * @return Reference to member thrust
 */
float& idl_msg::QuadAttitudeRateCommand::thrust()
{
    return m_thrust;
}

/*!
 * @brief This function sets a value in member roll_rate
 * @param _roll_rate New value for member roll_rate
 */
void idl_msg::QuadAttitudeRateCommand::roll_rate(
        float _roll_rate)
{
    m_roll_rate = _roll_rate;
}

/*!
 * @brief This function returns the value of member roll_rate
 * @return Value of member roll_rate
 */
float idl_msg::QuadAttitudeRateCommand::roll_rate() const
{
    return m_roll_rate;
}

/*!
 * @brief This function returns a reference to member roll_rate
 * @return Reference to member roll_rate
 */
float& idl_msg::QuadAttitudeRateCommand::roll_rate()
{
    return m_roll_rate;
}

/*!
 * @brief This function sets a value in member pitch_rate
 * @param _pitch_rate New value for member pitch_rate
 */
void idl_msg::QuadAttitudeRateCommand::pitch_rate(
        float _pitch_rate)
{
    m_pitch_rate = _pitch_rate;
}

/*!
 * @brief This function returns the value of member pitch_rate
 * @return Value of member pitch_rate
 */
float idl_msg::QuadAttitudeRateCommand::pitch_rate() const
{
    return m_pitch_rate;
}

/*!
 * @brief This function returns a reference to member pitch_rate
 * @return Reference to member pitch_rate
 */
float& idl_msg::QuadAttitudeRateCommand::pitch_rate()
{
    return m_pitch_rate;
}

/*!
 * @brief This function sets a value in member yaw_rate
 * @param _yaw_rate New value for member yaw_rate
 */
void idl_msg::QuadAttitudeRateCommand::yaw_rate(
        float _yaw_rate)
{
    m_yaw_rate = _yaw_rate;
}

/*!
 * @brief This function returns the value of member yaw_rate
 * @return Value of member yaw_rate
 */
float idl_msg::QuadAttitudeRateCommand::yaw_rate() const
{
    return m_yaw_rate;
}

/*!
 * @brief This function returns a reference to member yaw_rate
 * @return Reference to member yaw_rate
 */
float& idl_msg::QuadAttitudeRateCommand::yaw_rate()
{
    return m_yaw_rate;
}


size_t idl_msg::QuadAttitudeRateCommand::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;








    return current_align;
}

bool idl_msg::QuadAttitudeRateCommand::isKeyDefined()
{
    return false;
}

void idl_msg::QuadAttitudeRateCommand::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
         
}

