// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorCommand.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MotorCommand.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

MotorCommand::MotorCommand()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@21a947fe

    // m_speed com.eprosima.idl.parser.typecode.ArrayTypeCode@5606c0b


}

MotorCommand::~MotorCommand()
{


}

MotorCommand::MotorCommand(
        const MotorCommand& x)
{
    m_header = x.m_header;
    m_speed = x.m_speed;
}

MotorCommand::MotorCommand(
        MotorCommand&& x)
{
    m_header = std::move(x.m_header);
    m_speed = std::move(x.m_speed);
}

MotorCommand& MotorCommand::operator =(
        const MotorCommand& x)
{

    m_header = x.m_header;
    m_speed = x.m_speed;

    return *this;
}

MotorCommand& MotorCommand::operator =(
        MotorCommand&& x)
{

    m_header = std::move(x.m_header);
    m_speed = std::move(x.m_speed);

    return *this;
}

size_t MotorCommand::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);

    for(size_t a = 0; a < (4); ++a)
    {
        current_alignment += MotorSpeed::getMaxCdrSerializedSize(current_alignment);}

    return current_alignment - initial_alignment;
}

size_t MotorCommand::getCdrSerializedSize(
        const MotorCommand& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.header(), current_alignment);

    for(size_t a = 0; a < data.speed().size(); ++a)
    {
            current_alignment += MotorSpeed::getCdrSerializedSize(data.speed().at(a), current_alignment);
    }

    return current_alignment - initial_alignment;
}

void MotorCommand::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_speed;


}

void MotorCommand::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_speed;

}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void MotorCommand::header(
        const Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void MotorCommand::header(
        Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const Header& MotorCommand::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
Header& MotorCommand::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member speed
 * @param _speed New value to be copied in member speed
 */
void MotorCommand::speed(
        const std::array<MotorSpeed, 4>& _speed)
{
    m_speed = _speed;
}

/*!
 * @brief This function moves the value in member speed
 * @param _speed New value to be moved in member speed
 */
void MotorCommand::speed(
        std::array<MotorSpeed, 4>&& _speed)
{
    m_speed = std::move(_speed);
}

/*!
 * @brief This function returns a constant reference to member speed
 * @return Constant reference to member speed
 */
const std::array<MotorSpeed, 4>& MotorCommand::speed() const
{
    return m_speed;
}

/*!
 * @brief This function returns a reference to member speed
 * @return Reference to member speed
 */
std::array<MotorSpeed, 4>& MotorCommand::speed()
{
    return m_speed;
}

size_t MotorCommand::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool MotorCommand::isKeyDefined()
{
    return false;
}

void MotorCommand::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
